apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: adservice
  description: Ad Service for Online Boutique
  tags:
    - java
    - backend
    - grpc
  links:
    - url: https://github.com/googlecloudplatform/microservices-demo
      title: Online Boutique - Upstream repo
      icon: help
spec:
  type: service
  lifecycle: experimental
  owner: cpet
  system: online-boutique
  # dependsOn: ['component:artists-db']
  apiConsumedBy: ['component:frontend']